Models/Contact.cs
using System.ComponentModel.DataAnnotations;

namespace testASP.Models
{
    public class Contact
    {
        [Display(Name = "Ваш Email")]
        public DateOnly JoiningDate { get; set; }

        [Display(Name = "Ваше ім'я")]
        [Required(ErrorMessage = "Ім'я має бути обов'язково")]
        public string Name { get; set; }

        [Display(Name = "Ваше прізвище")]
        [Required(ErrorMessage = "Прізвище має бути обов'язково")]
        public string SurName { get; set; }
  
        [Display(Name = "Ваш телефон")]
        [Required(ErrorMessage = "Телефон має бути обов'язково")]
        public int Telephone { get; set; }

        [Display(Name = "Ваш Email")]
        [Required(ErrorMessage = "Email має бути обов'язково")]
        [UIHint("EmailAddress")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Введіть пароль")]
        [Display(Name = "Введіть пароль")]
        [StringLength(15, MinimumLength = 6)]
        [Compare("PasswordConfirm")]
        [UIHint("Password")]
        public string Password { get; set; }

        [Display(Name = "Введіть пароль повторно")]
        [StringLength(15, MinimumLength = 6)]
        [UIHint("Password")]
        public string PasswordConfirm { get; set; }

    }
}

Models/ErrorViewModel.cs
namespace testASP.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Photo.cs
using System.ComponentModel.DataAnnotations;

namespace testASP.Models
{
    public class Photo
    {
        [Display(Name = "Зимня казка")]
        public string Name { get; }
    }
}

Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;
using testASP.Models;

namespace testASP.Controllers
{
    public class ContactsController : Controller
    {

        public IActionResult Index()//contacts
        {
            Contact model = new()
            {
                JoiningDate = DateOnly.FromDateTime(DateTime.Today),
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Check(Contact contact)
        {
            if(ModelState.IsValid)
            {
                return Redirect("/Photo");
            }
            return View("Index");
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using testASP.Models;

namespace testASP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public ViewResult Db()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PhotoController.cs
using Microsoft.AspNetCore.Mvc;

namespace testASP.Controllers
{
    public class PhotoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Contacts/Index.cshtml
@model Contact

@{
    ViewData["Title"] = "Реєстрація";
}

<h1>РЕЄСТРАЦІЯ</h1>

<form method="post" asp-controller="Contacts" asp-action="Check">
    <label asp-for="Name"></label>
    <input asp-for="Name">
    <span asp-validation-for="Name"></span>

     <label asp-for="SurName"></label>
    <input asp-for="SurName">
    <span asp-validation-for="SurName"></span>

     <label asp-for="Email"></label>
    <input asp-for="Email">
    <span asp-validation-for="Email"></span>

    <div>
         <label asp-for="Password"></label>
         <input  asp-for="Password" >
         <span asp-validation-for="Password"></span>
    </div>
    <div >
         <label asp-for="PasswordConfirm"></label>
         <input asp-for="PasswordConfirm">
          <span asp-validation-for="Password"></span>
    </div>
    <div >
         <label asp-for="JoiningDate"></label>
         <input asp-for="JoiningDate">
         
    </div>
    
   
    <input type="submit" value="Отправить" />
</form>

Views/Home/Db.cshtml
@model Contact

@{
    ViewData["Title"] = "Db";
}
<h2>Робота з базами даних</h2>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "ДОМАШНЄ ЗАВДАННЯ 2";
}

<h1>ДОМАШНЄ ЗАВДАННЯ 2</h1><br>
<h2>Створити сервіс валідації даних</h2><br>

Views/Photo/Index.cshtml
@model Photo
@{
    ViewData["Title"] = "Успішна реєстрація";
}

<h1>Вітаю! Pеєстрація пройшла успішно!</h1>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="my.css">
</head>
<body>
    <form method="post" asp-controller="Photo">
    <label asp-for="Name"></label>

</form>
  <div class="flex">
     <div class="banner">
      <img src="img/50.jpg" alt="">
    </div>
  </div>

</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/my.css" type="text/css" />

</head>
<body>
    <header>
        <span class="logo">ASP_HW_2</span>
        <nav>
            <ul>
                <li><a href="/">Головна сторінка</a></li>
                <li><a href="/contacts">Реєстрація</a></li>
                 <li><a asp-controller="Home" asp-action="Db">Робота з базами даних</a></li>
            </ul>
        </nav>   
    </header>
        <main>     
            @RenderBody()
        </main>
    <footer>Усі права захищені</footer>
   
</body>
</html>